import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ----- Kinship & Co Material 3 tokens -----
        "surface": "#f6faff",
        "surface-dim": "#cfdce7",
        "surface-bright": "#f6faff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ebf5ff",
        "surface-container": "#e3effb",
        "surface-container-high": "#ddeaf5",
        "surface-container-highest": "#d8e4f0",
        "on-surface": "#111d25",
        "on-surface-variant": "#41484e",
        "inverse-surface": "#26323b",
        "inverse-on-surface": "#e6f2fe",
        "outline": "#71787f",
        "outline-variant": "#c0c7cf",
        "surface-tint": "#1c648e",
        "primary": "#1c648e",
        "on-primary": "#ffffff",
        "primary-container": "#7cb9e8",
        "on-primary-container": "#00496d",
        "inverse-primary": "#90cdfd",
        "secondary": "#2c6956",
        "on-secondary": "#ffffff",
        "secondary-container": "#aeedd5",
        "on-secondary-container": "#316d5b",
        "tertiary": "#765b06",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d2af58",
        "on-tertiary-container": "#574200",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#cae6ff",
        "primary-fixed-dim": "#90cdfd",
        "on-primary-fixed": "#001e30",
        "on-primary-fixed-variant": "#004b70",
        "secondary-fixed": "#b1efd8",
        "secondary-fixed-dim": "#96d3bd",
        "on-secondary-fixed": "#002118",
        "on-secondary-fixed-variant": "#0d503f",
        "tertiary-fixed": "#ffdf96",
        "tertiary-fixed-dim": "#e7c269",
        "on-tertiary-fixed": "#251a00",
        "on-tertiary-fixed-variant": "#594400",
        "background": "#f6faff",
        "on-background": "#111d25",
        "surface-variant": "#d8e4f0",

        // ----- Bakoverkompatibilitet: gammel brand-skala mappes til primary-skalaen -----
        brand: {
          50: "#f0f7fd",
          100: "#cae6ff",
          200: "#90cdfd",
          300: "#7cb9e8",
          400: "#3a8ec0",
          500: "#1c648e",
          600: "#1c648e",
          700: "#00496d",
          800: "#004b70",
          900: "#001e30",
        },
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "16px",
        "container-margin": "20px",
      },
      fontFamily: {
        sans: ["Nunito Sans", "system-ui", "-apple-system", "sans-serif"],
        display: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Nunito Sans", "sans-serif"],
        "body-md": ["Nunito Sans", "sans-serif"],
        "label-lg": ["Nunito Sans", "sans-serif"],
        "label-sm": ["Nunito Sans", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      boxShadow: {
        // Soft lifted-paper stil
        soft: "0 4px 20px -4px rgba(28, 100, 142, 0.08)",
        card: "0 1px 3px rgba(17, 29, 37, 0.04), 0 4px 12px rgba(17, 29, 37, 0.04)",
        pop: "0 8px 24px -4px rgba(17, 29, 37, 0.12), 0 4px 8px -2px rgba(17, 29, 37, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
