// Forhåndsdefinerte ikoner for gjøremål — emoji-baserte for enkelhet og
// universalt utseende på tvers av enheter.

export const CHORE_ICONS: Array<{ icon: string; label: string }> = [
  { icon: "✅", label: "Generelt" },
  { icon: "🧹", label: "Feie" },
  { icon: "🧺", label: "Vaskekurv" },
  { icon: "🧼", label: "Såpe" },
  { icon: "🛏️", label: "Re seng" },
  { icon: "🚿", label: "Dusje" },
  { icon: "🛁", label: "Bade" },
  { icon: "🪥", label: "Tannpuss" },
  { icon: "🍽️", label: "Oppvask" },
  { icon: "🍳", label: "Lage mat" },
  { icon: "🥗", label: "Måltid" },
  { icon: "🛒", label: "Handle" },
  { icon: "🚮", label: "Søppel" },
  { icon: "🌱", label: "Plante" },
  { icon: "🌿", label: "Vanne" },
  { icon: "💧", label: "Vann" },
  { icon: "🐕", label: "Hund" },
  { icon: "🐱", label: "Katt" },
  { icon: "🚗", label: "Bil" },
  { icon: "⛽", label: "Bensin" },
  { icon: "🪴", label: "Plante" },
  { icon: "📚", label: "Lese" },
  { icon: "✏️", label: "Lekser" },
  { icon: "📝", label: "Notere" },
  { icon: "💊", label: "Medisin" },
  { icon: "🧽", label: "Skure" },
  { icon: "👕", label: "Klær" },
  { icon: "🪞", label: "Speil" },
  { icon: "📦", label: "Rydde" },
  { icon: "🧯", label: "Sikkerhet" },
  { icon: "🔧", label: "Reparere" },
  { icon: "🧴", label: "Krem" },
  { icon: "🪑", label: "Møbler" },
  { icon: "🚽", label: "Toalett" },
  { icon: "🍞", label: "Brød" },
  { icon: "🥛", label: "Melk" },
  { icon: "🐟", label: "Fisk" },
  { icon: "📬", label: "Post" },
  { icon: "🌳", label: "Hage" },
  { icon: "❄️", label: "Måke snø" },
];
