/**
 * Hjelpetekster for utrednings-tester.
 * Skrevet for Rakel (14 år) – enkelt norsk språk.
 *
 * Format: { [testId]: { [spørsmålsNummer]: string } }
 */

export const TEST_HELP_TEXTS: Record<string, Record<number, string>> = {
  aq50: {
    1:  "Handler om hva du foretrekker – å gjøre ting SAMMEN med venner/familie, eller å gjøre ting ALENE. Tenk på hva du oftest velger og trives best med.",
    2:  "Liker du rutiner og å gjøre ting på nøyaktig samme måte hver gang? F.eks. alltid spise frokost i samme rekkefølge, ta samme vei til skolen, eller følge et bestemt mønster?",
    3:  "Kan du se bilder «inne i hodet» når du tenker? Prøv: se for deg et rødt eple. Dukker det faktisk opp et bilde i tankene dine, eller tenker du mer i ord og følelser?",
    4:  "Skjer det at du er så konsentrert om noe du holder på med at du 'glemmer' alt annet rundt deg – som at noen snakker til deg, at det er stille eller at tid går?",
    5:  "Er du ekstra sensitiv for lyder? F.eks. legger du merke til en dryppende kran, summing fra lamper, fugler utenfor eller andre svake lyder som andre ikke reagerer på?",
    6:  "Legger du automatisk merke til tall og bokstavrekker du ser rundt deg – som bilskilt, priser, bussnumre – uten å prøve å huske dem?",
    7:  "Har det skjedd at du sa noe du mente var helt greit, men en venn eller voksen ble fornærmet eller sa at det var uhøflig – uten at du skjønte hvorfor de reagerte slik?",
    8:  "Når du leser en bok – ser du for deg ansiktet, klærne og utseendet til personene i historien? Får du et tydelig bilde av dem i tankene?",
    9:  "Er du spesielt interessert i datoer? F.eks. husker du lett historiske årstall, fødselsdatoer eller nøyaktig dato for når ting skjedde?",
    10: "Når du er i en gruppe der flere snakker – klarer du å følge med på hva alle de ulike personene sier, eller er det vanskelig å ha oversikt over alle samtalene på en gang?",
    11: "Er det generelt ENKELT for deg å være i sosiale situasjoner – som pauser på skolen, fester, eller å prate med folk du ikke kjenner så godt?",
    12: "Legger du merke til småting som andre ikke ser? F.eks. at en gjenstand er flyttet litt, at noe mangler, at noen har kuttet håret litt, eller detaljer i bilder?",
    13: "Hvis du måtte velge: ville du heller tilbringe ettermiddagen på et rolig sted (som et bibliotek) eller på en fest med mange folk? Velg hva du egentlig foretrekker.",
    14: "Kan du lett finne på egne historier? F.eks. dikte opp et eventyr spontant, lage en fantasy-verden i hodet, eller fortelle en spennende oppdiktet fortelling?",
    15: "Er du mer interessert i FOLK – hva de tenker, føler og gjør – enn i TING, systemer, fakta eller hobbyer? Hva tar tankene dine mest til?",
    16: "Har du én eller noen interesser du er EKSTRA opptatt av – noe du kan snakke lenge om, vet veldig mye om, og gjerne bruker mye tid på?",
    17: "Liker du 'small talk' – lett, uforpliktende prat om hverdagslige ting? F.eks. snakke om været, hva du gjorde i helgen, eller 'hva skjer?'-samtaler.",
    18: "Har noen sagt til deg at de ikke klarer å si noe fordi du snakker mye? Eller merker du selv at du tar opp mye plass i samtaler og at andre sjelden kommer til?",
    19: "Er du spesielt fascinert av tall – matte, statistikk, tallmønstre eller regning – mer enn det de fleste andre er?",
    20: "Når du leser en bok eller ser en film – synes du det er vanskelig å forstå HVORFOR karakterene gjør det de gjør? Å skjønne planene og tankene deres?",
    21: "Skjønnlitteratur er oppdiktede romaner og noveller. Liker du å lese slike bøker, eller foretrekker du faktabøker, tegneserier eller annet?",
    22: "Er det vanskelig for deg å bli kjent med nye folk og bygge vennskap fra grunnen av – å gå fra fremmed til venn?",
    23: "Ser du mønstre overalt – i fliser, tall, natur, musikk, hendelser? F.eks. symmetri, gjentakende rekkefølger eller former som du legger merke til automatisk?",
    24: "Teater handler om å se en fortelling med karakterer og drama. Museum handler om å se gjenstander, fakta og utstillinger. Hva ville du helst gjøre?",
    25: "Hvis den vanlige rutinen din plutselig endres – f.eks. en plan avlyses, timen er byttet ut, eller du ikke kan gjøre noe du pleier – plager det deg mye?",
    26: "Hender det at samtaler 'stopper opp' og du ikke vet hva du skal si videre? At det blir stille og du ikke klarer å finne på noe nytt å si?",
    27: "Å «lese mellom linjene» betyr å forstå det folk egentlig mener – ikke bare ordene de sier. F.eks. når noen sier «det er greit» men egentlig er skuffet. Klarer du det?",
    28: "Fokuserer du mest på DETALJER og enkeltting, eller på HELHETEN og hvordan alt henger sammen? Hva er din naturlige måte å se ting på?",
    29: "Husker du lett tall som telefonnumre, koder og passord – eller glemmer du dem fort og trenger å skrive dem ned?",
    30: "Legger du merke til forandringer rundt deg? F.eks. at en stol er flyttet, at noe mangler fra bordet, eller at noen har en ny frisyre?",
    31: "Kan du se på en person om de begynner å kjede seg mens du snakker – ved å lese ansiktsuttrykket og kroppsspråket deres?",
    32: "Klarer du å gjøre to ting samtidig? F.eks. lytte til musikk og lese lekser, eller snakke og rydde rommet? Eller trenger du å fokusere på én ting av gangen?",
    33: "I en telefonsamtale (der du ikke kan se ansiktet til den du snakker med) – klarer du å vite når den andre er ferdig med å snakke og det er din tur?",
    34: "Liker du å gjøre ting SPONTANT – uten plan, bare finne på noe i øyeblikket? Eller foretrekker du å planlegge og vite hva som skal skje?",
    35: "Hender det at alle rundt deg ler av en vits, men det tar litt tid før du skjønner hva som er morsomt – eller at du trenger å få vitsen forklart?",
    36: "Kan du lese ansiktsuttrykk godt? F.eks. se om noen er lei seg, glad, sint, nervøs eller skuffet bare ved å se på ansiktet deres?",
    37: "Hvis du holder på med noe og blir avbrutt – klarer du lett å begynne igjen der du slapp? Eller er det frustrerende og vanskelig å komme tilbake til det?",
    38: "«Small-talk» er lett, uformell prat med folk du ikke kjenner så godt – som naboer, kjøpmannsdisken, eller nye klassekamerater. Er du komfortabel med det?",
    39: "Merker du at folk snakker om deg på andre siden av rommet, selv om du ikke hører ordene tydelig? Er du sensitiv for slike sosiale signaler rundt deg?",
    40: "Når du leser en bok eller artikkel – klarer du lett å forstå hva forfatteren egentlig vil si? Hva budskapet er, og hva de har tenkt på?",
    41: "Samler du på noe – eller liker du å sortere og kategorisere ting systematisk? F.eks. figurer, kort, musikk, filmer, fakta, eller noe annet du ordner i kategorier?",
    42: "Klarer du å 'sette deg inn i' en annen persons situasjon? F.eks. forestille deg hvordan det kjennes å leve et helt annet liv, ha andre tanker og andre erfaringer enn deg?",
    43: "Liker du å ha en detaljert plan for ting du skal gjøre? F.eks. vite nøyaktig hva som skjer, hvem som er der og i hvilken rekkefølge ting skjer?",
    44: "Liker du sosiale begivenheter generelt – som bursdagsfester, familiesammenkomster, klassefester og lignende arrangementer?",
    45: "Er det vanskelig å forstå HVORFOR folk gjør det de gjør? F.eks. forstå om en person er snill, vil lure deg, er sjalu, eller bare er genuint vennlig?",
    46: "Blir du urolig eller nervøs når du er i en situasjon du ikke har vært i før? F.eks. nytt sted, ny skole, ukjente folk eller aktiviteter du ikke kjenner fra før?",
    47: "Synes du det er hyggelig å bli kjent med nye folk – folk du aldri har møtt før?",
    48: "En diplomat er flink til å si ting på en måte som ikke sårer noen og som får folk til å forstå hverandre. Er du flink til å håndtere vanskelige situasjoner mellom folk?",
    49: "Husker du vennenes bursdager og andre viktige datoer? Er du generelt god til å huske slike ting?",
    50: "«Late som»-lek er fantasilek der man later som man er noe annet – at pinnene er sverd, teppet er et skip, eller at man er en karakter i et eventyr. Er slik lek lett for deg?",
  },

  // ── BRIEF®-SR (Norsk) ────────────────────────────────────────────────────────
  brief_sr_no: {
    1:  "Handler om du klarer å sitte rolig – f.eks. på skolen, i sofaen eller i kø. Beveger du deg mye, rister på beina eller reiser deg hele tiden?",
    2:  "Hvis du vil løse noe på én bestemt måte og noen foreslår noe annet – klarer du å prøve det? Eller insisterer du på din egen metode?",
    3:  "Arbeidsminnet er hjernens midlertidige notisblokk. Hvis noen ber deg om tre ting raskt etter hverandre – husker du alle tre, eller faller noen bort?",
    4:  "Starter du med ting uten å sjekke at du har alt du trenger? F.eks. begynner du på lekser uten blyant, eller lager mat uten å sjekke ingrediensene?",
    5:  "Hvis noe lite går galt – f.eks. at noe søles, at du mister noe, eller at noe ikke blir som planlagt – reagerer du veldig sterkt? Blir det mye større enn det trengs?",
    6:  "Er skrivebordet eller arbeidsplassen din uorganisert – med papirer, ting og gjenstander blandet om hverandre? Eller holder du det ryddig?",
    7:  "Legger du merke til om det du gjør plager andre rundt deg? F.eks. om du snakker for mye, er for høylytt, eller gjør noe som irriterer noen?",
    8:  "Jobber eller prosjekter som tar lang tid – som en stor skoleoppgave eller et hobbyprosjekt. Klarer du å jobbe med det over mange dager til det er ferdig?",
    9:  "Hvis noe som var planlagt plutselig endres – en avlyst aktivitet, ny plan, eller uventet hendelse – blir du veldig urolig eller irritert av det?",
    10: "Plasserer du deg for nær andre fysisk? F.eks. stå veldig tett bak noen i kø, sette deg for nær noen på bussen, eller gå inn i andres personlige rom?",
    11: "Hvis noe ikke fungerer – klarer du å prøve noe helt annet? Eller fortsetter du å gjøre det på samme måte selv om det ikke hjelper?",
    12: "Klarer du å holde fokus lenge nok på én ting? Eller hopper tankene dine raskt videre til noe annet, og det er vanskelig å konsentrere seg?",
    13: "Tenker du på forhånd hva du trenger å gjøre til neste uke, neste dag, eller til en bestemt aktivitet? Eller tar du ting som de kommer?",
    14: "Et sinneutbrudd er når du plutselig blir veldig sint – kanskje roper, slår, eller kaster ting. Skjer dette av og til, eller sjelden/aldri?",
    15: "Mister eller forlegger du ting ofte? F.eks. at du ikke finner leksene, mister bussbilletten, eller ikke vet hvor du la noe?",
    16: "Merker du når andre reagerer negativt på det du gjør – kanskje at de trekker seg unna eller ser sure ut? Eller skjønner du det gjerne etterpå?",
    17: "Klarer du å fullføre en oppgave fra start til slutt uten at noen hjelper deg i gang, minner deg på, eller følger opp underveis?",
    18: "Hvis noe uventet skjer i løpet av dagen – en vikarlærer, timene er byttet om, eller noe du hadde planlagt faller bort – blir du veldig urolig?",
    19: "Klarer du å vente på din tur – i kø, i samtaler, i spill? Eller er det vanskelig å holde tilbake og la andre gå/snakke først?",
    20: "Bruker du lengre tid enn andre på å bli ferdig med oppgaver på skolen eller hjemme? Ikke fordi du ikke kan, men fordi det bare tar lenger tid?",
    21: "Har du noen gang gjort leksene, men glemt å levere dem inn? Oppgaven er klar, men du glemte å faktisk sende eller levere den?",
    22: "Er det vanskelig å komme deg i gang om morgenen – å stå opp, spise, kle på seg og komme deg dit du skal innen avtalt tid?",
    23: "Lar tårene komme lett? F.eks. ved frustrasjoner, skuffelser, eller ting som ikke er veldig alvorlige – at du begynner å gråte av seg selv?",
    24: "Glemmer du bøker, lekseark, gymtøy eller andre ting du trenger hjemme? Reiser du hjem uten det du skulle ha med?",
    25: "Når du er i en gruppe – f.eks. i klassen, blant venner eller i familien – er du bevisst på hvordan du oppfører deg? Eller tenker du ikke så mye på det?",
    26: "Klarer du å bli ferdig med oppgavene du starter? F.eks. skoleoppgaver, prosjekter eller andre ting du er satt til å gjøre – fullfører du dem?",
    27: "Er det vanskelig når noe i hverdagen endrer seg? F.eks. at dere spiser annen mat enn vanlig, at du er på et annet sted, eller at rutinene er annerledes?",
    28: "Hender det at du hopper inn midt i samtaler eller aktiviteter der andre holder på? F.eks. å begynne å snakke mens noen andre snakker?",
    29: "Når du møter et problem – klarer du å tenke ut ulike mulige løsninger? Eller er det vanskelig å finne nye ideer og måter å angripe det på?",
    30: "Oppgaver med mange steg – som en flertrinns matteoppgave eller en oppskrift – er disse vanskelige å holde oversikt over og gjennomføre i riktig rekkefølge?",
    31: "Starter du med skoleoppgaver uten å planlegge – f.eks. begynner du en stor innlevering dagen før, eller vet du ikke hva som må gjøres til neste uke?",
    32: "Har du noen ganger sterke følelsesutbrudd – raseri, gråt, frustrasjon – som virker å komme av lite? Som om den ytre grunnen ikke forklarer reaksjonen?",
    33: "Er skolesekken din rotet – med ting blandet, papirer krøllet, og vanskelig å finne det du leter etter? Eller er den ryddig og organisert?",
    34: "Vet du hvilke ting du er flink til og hvilke du sliter mer med? Eller prøver du noen ganger ting som er altfor vanskelig – eller altfor lett – uten å ha tenkt på det?",
    35: "Starter du mange ting, men fullfører ikke alle? F.eks. hobbyprosjekter, tegninger, bøker du leser halvveis, eller oppgaver du ikke ble ferdig med?",
    36: "Tar det lang tid å bli komfortabel i en ny setting – ny klasse, ny fritidsaktivitet, nye venner? Eller er du ganske rask til å tilpasse deg?",
    37: "Impulsiv betyr at du handler uten å tenke deg om først. F.eks. si noe du angrer på rett etter, ta en beslutning veldig raskt, eller gjøre noe uten å planlegge.",
    38: "Skjer det at du vet svaret hjemme, men på selve prøven er det vanskelig å vise det? At kunnskapen er der, men det er vanskelig å få den frem under press?",
    39: "Hender det at du er midt i noe – f.eks. henter noe fra et annet rom – og plutselig ikke husker hva du var på vei for å gjøre?",
    40: "Når du skriver en tekst eller rapport – er det vanskelig å strukturere den med innledning, hoveddel og avslutning? Er det vanskelig å holde orden i det du skriver?",
    41: "Begynner du lett å gråte – kanskje av frustrasjon, skuffelse, eller noe som ikke er så alvorlig? Selv om du ikke vil gråte, kommer det bare av seg selv?",
    42: "Er det vanskelig å møte opp til riktig tid på skolen, møter, trening eller avtaler? Kommer du ofte for sent, selv om du prøver å rekke det?",
    43: "Skjønner du vanligvis at det du gjør plager noen? Eller finner du det ut etterpå – kanskje fordi noen sier ifra til deg?",
    44: "Har du mange ideer og planer, men klarer ikke å omsette dem til handling? Tanken er der, men du kommer ikke i gang – eller fullfører ikke?",
    45: "Er det vanskelig å stoppe med noe du holder på med og begynne på noe annet? F.eks. å slutte å spille for å gjøre lekser, eller avslutte en aktivitet?",
    46: "Hender det at du reiser deg, går rundt, eller forlater plassen din på tidspunkter der det ikke er passende – f.eks. midt i timen eller under måltider?",
    47: "Fokuserer du så mye på én detalj at du mister oversikten over hva som er viktigst? F.eks. bruker mye tid på én liten del av en oppgave og glemmer resten?",
    48: "Hvis noen ber deg hente noe – f.eks. 'hent brillene fra soverommet' – går du dit og kan ikke huske hva det var du skulle ha?",
    49: "Tenker du over hva som kan gå galt, eller hva du trenger, FØR noe skjer? Eller oppdager du problemer først når de dukker opp?",
    50: "Sammenlignet med vennene dine – virker du mer følsom eller sterkere påvirket av ting? F.eks. at du ble veldig oppskaket av noe andre syntes var greit?",
    51: "Bruker du mye tid på å lete etter ting du trenger? Vet du vanligvis hvor tingene dine er, eller 'forsvinner' de stadig?",
    52: "Slurveifeil er feil som skjer fordi man ikke var nøye nok – ikke fordi man ikke kan svaret. Regner du feil fordi du leste oppgaven raskt, eller glemmer du tegnsetting?",
    53: "Klarer du å gjøre ferdig oppgaver som husarbeid eller lekser fra start til slutt? Eller stopper det opp underveis og du blir ikke ferdig?",
    54: "Sammenlignet med vennene dine – mister du kontroll over reaksjonene dine (sinne, frustrasjon, gråt) mer enn det virker som de gjør?",
    55: "Når du støter på et problem – er det vanskelig å tenke ut ULIKE mulige løsninger? Ser du bare én måte å gjøre det på?",
    56: "Hender det at du hopper fra tema til tema når du snakker, uten at det henger helt sammen? At lytteren kanskje ikke henger med i overgangene?",
    57: "Har du et mål – spare penger, bli bedre på noe, oppnå noe? Klarer du å gjøre de nødvendige stegene over tid for faktisk å nå det?",
    58: "Er du rask til å bli opprørt eller frustrert? F.eks. når ting ikke går som planlagt, når du gjør feil, eller når du ikke får det til?",
    59: "Er skolearbeidet eller andre ting du leverer ofte slurvet – dårlig håndskrift, ufullstendige svar, ustrukturert? Eller er du vanligvis nøye?",
    60: "Når du er ferdig med en oppgave – leser du gjennom den for å sjekke om det er feil? Eller leverer du uten å dobbeltsjekke?",
    61: "Hender det at du sier noe og angrer rett etterpå – fordi du burde ha tenkt deg om? At ordene kom ut før du rakk å vurdere om det var lurt å si dem?",
    62: "Er det vanskelig å slippe noe du er opptatt av? F.eks. at du snakker om det samme, tenker på det hele tiden, eller ikke klarer å gå videre til noe annet?",
    63: "Kan du glemme noe etter bare noen minutter? F.eks. at noen fortalte deg et telefonnummer eller en beskjed og det er borte allerede?",
    64: "Klarer du å sette i gang med ting selv – uten at noen minner deg på eller hjelper deg i gang? Eller er det vanskelig å starte noe på egenhånd?",
    65: "Reagerer du sterkt på ting som er ganske små – f.eks. at noe søles, at du tar feil busstopp, eller at noen sa noe uheldig? Oppleves det som veldig viktig?",
    66: "Snakker du noen ganger for høyt uten å merke det? At andre ber deg dempe deg, eller at du selv er overrasket over lydnivået ditt?",
    67: "Når noe ikke fungerer og du setter deg fast – klarer du å finne på en alternativ plan? Eller er det vanskelig å tenke nytt og prøve noe annet?",
    68: "Hender det at du plutselig begynner å snakke om noe helt annet midt i en samtale – uten at overgangen er veldig tydelig for den du snakker med?",
    69: "Å prioritere betyr å velge hva som er viktigst å gjøre NESTE. Er det vanskelig å bestemme seg for hva du bør gjøre først – f.eks. lekser vs. fritid vs. husarbeid?",
    70: "Overreagere er når reaksjonen din er mye sterkere enn situasjonen tilsier. F.eks. bli veldig sint av noe lite, eller veldig trist av noe som egentlig ikke er så farlig.",
    71: "Skjer det at du er for vill, bråkete eller ute av kontroll? At andre kanskje synes du er for mye, eller at du selv kjenner at du ikke klarer å roe ned?",
    72: "Vet du stoffet, men klarer ikke å levere det på prøven? Som om det er vanskeligere å hente frem kunnskapen under press enn når du er hjemme og øver?",
    73: "Hvis læreren forteller hva du skal gjøre – husker du instruksjonen frem til du er ferdig? Eller glemmer du deler av den underveis i oppgaven?",
    74: "Klarer du å fordele tid og energi mellom skole, fritid og andre forpliktelser? Eller er det vanskelig å få det til å gå opp?",
    75: "Overveldet er en følelse av at det er for mye å takle på en gang. Skjer dette ofte – f.eks. av mange ting som skjer samtidig, mye lekser, eller mange inntrykk?",
    76: "Hender det at du tenker høyt – snakker til deg selv, mumler, eller kommenterer det du holder på med mens du jobber? Gjør du det for å hjelpe deg å holde fokus?",
    77: "Er du den som er sist ferdig med oppgaver i klassen, eller bruker du generelt lengre tid enn andre på å fullføre ting – ikke fordi det er for vanskelig, men det tar tid?",
    78: "Distré er å glemme ting, miste tråden, eller ikke ha hodet med seg. F.eks. legge nøklene på feil sted, glemme hva du kom inn i rommet for, eller tenke på noe annet.",
    79: "Hender det at du begynner å snakke på tidspunkter der det ikke passer – f.eks. under filmvisning, når læreren snakker, eller avbryter en rolig stund?",
    80: "Tenker du gjennom hva som kan skje ETTERPÅ, før du gjør noe? Eller handler du og tenker på konsekvensene etterpå?",
  },
};
