/**
 * Hjelpetekster for utrednings-tester.
 * Skrevet for Rakel (14 år) – enkelt norsk språk.
 *
 * Format: { [testId]: { [spørsmålsNummer]: string } }
 */

export const TEST_HELP_TEXTS: Record<string, Record<number, string>> = {
  aq50: {
    1:  "Handler om hva du foretrekker – å gjøre ting SAMMEN med venner/familie, eller å gjøre ting ALENE. Tenk på hva du oftest velger og trives best med.",
    2:  "Liker du rutiner og å gjøre ting på nøyaktig samme måte hver gang? F.eks. alltid spise frokost i samme rekkefølge, ta samme vei til skolen, eller følge et bestemt mønster?",
    3:  "Kan du se bilder «inne i hodet» når du tenker? Prøv: se for deg et rødt eple. Dukker det faktisk opp et bilde i tankene dine, eller tenker du mer i ord og følelser?",
    4:  "Skjer det at du er så konsentrert om noe du holder på med at du 'glemmer' alt annet rundt deg – som at noen snakker til deg, at det er stille eller at tid går?",
    5:  "Er du ekstra sensitiv for lyder? F.eks. legger du merke til en dryppende kran, summing fra lamper, fugler utenfor eller andre svake lyder som andre ikke reagerer på?",
    6:  "Legger du automatisk merke til tall og bokstavrekker du ser rundt deg – som bilskilt, priser, bussnumre – uten å prøve å huske dem?",
    7:  "Har det skjedd at du sa noe du mente var helt greit, men en venn eller voksen ble fornærmet eller sa at det var uhøflig – uten at du skjønte hvorfor de reagerte slik?",
    8:  "Når du leser en bok – ser du for deg ansiktet, klærne og utseendet til personene i historien? Får du et tydelig bilde av dem i tankene?",
    9:  "Er du spesielt interessert i datoer? F.eks. husker du lett historiske årstall, fødselsdatoer eller nøyaktig dato for når ting skjedde?",
    10: "Når du er i en gruppe der flere snakker – klarer du å følge med på hva alle de ulike personene sier, eller er det vanskelig å ha oversikt over alle samtalene på en gang?",
    11: "Er det generelt ENKELT for deg å være i sosiale situasjoner – som pauser på skolen, fester, eller å prate med folk du ikke kjenner så godt?",
    12: "Legger du merke til småting som andre ikke ser? F.eks. at en gjenstand er flyttet litt, at noe mangler, at noen har kuttet håret litt, eller detaljer i bilder?",
    13: "Hvis du måtte velge: ville du heller tilbringe ettermiddagen på et rolig sted (som et bibliotek) eller på en fest med mange folk? Velg hva du egentlig foretrekker.",
    14: "Kan du lett finne på egne historier? F.eks. dikte opp et eventyr spontant, lage en fantasy-verden i hodet, eller fortelle en spennende oppdiktet fortelling?",
    15: "Er du mer interessert i FOLK – hva de tenker, føler og gjør – enn i TING, systemer, fakta eller hobbyer? Hva tar tankene dine mest til?",
    16: "Har du én eller noen interesser du er EKSTRA opptatt av – noe du kan snakke lenge om, vet veldig mye om, og gjerne bruker mye tid på?",
    17: "Liker du 'small talk' – lett, uforpliktende prat om hverdagslige ting? F.eks. snakke om været, hva du gjorde i helgen, eller 'hva skjer?'-samtaler.",
    18: "Har noen sagt til deg at de ikke klarer å si noe fordi du snakker mye? Eller merker du selv at du tar opp mye plass i samtaler og at andre sjelden kommer til?",
    19: "Er du spesielt fascinert av tall – matte, statistikk, tallmønstre eller regning – mer enn det de fleste andre er?",
    20: "Når du leser en bok eller ser en film – synes du det er vanskelig å forstå HVORFOR karakterene gjør det de gjør? Å skjønne planene og tankene deres?",
    21: "Skjønnlitteratur er oppdiktede romaner og noveller. Liker du å lese slike bøker, eller foretrekker du faktabøker, tegneserier eller annet?",
    22: "Er det vanskelig for deg å bli kjent med nye folk og bygge vennskap fra grunnen av – å gå fra fremmed til venn?",
    23: "Ser du mønstre overalt – i fliser, tall, natur, musikk, hendelser? F.eks. symmetri, gjentakende rekkefølger eller former som du legger merke til automatisk?",
    24: "Teater handler om å se en fortelling med karakterer og drama. Museum handler om å se gjenstander, fakta og utstillinger. Hva ville du helst gjøre?",
    25: "Hvis den vanlige rutinen din plutselig endres – f.eks. en plan avlyses, timen er byttet ut, eller du ikke kan gjøre noe du pleier – plager det deg mye?",
    26: "Hender det at samtaler 'stopper opp' og du ikke vet hva du skal si videre? At det blir stille og du ikke klarer å finne på noe nytt å si?",
    27: "Å «lese mellom linjene» betyr å forstå det folk egentlig mener – ikke bare ordene de sier. F.eks. når noen sier «det er greit» men egentlig er skuffet. Klarer du det?",
    28: "Fokuserer du mest på DETALJER og enkeltting, eller på HELHETEN og hvordan alt henger sammen? Hva er din naturlige måte å se ting på?",
    29: "Husker du lett tall som telefonnumre, koder og passord – eller glemmer du dem fort og trenger å skrive dem ned?",
    30: "Legger du merke til forandringer rundt deg? F.eks. at en stol er flyttet, at noe mangler fra bordet, eller at noen har en ny frisyre?",
    31: "Kan du se på en person om de begynner å kjede seg mens du snakker – ved å lese ansiktsuttrykket og kroppsspråket deres?",
    32: "Klarer du å gjøre to ting samtidig? F.eks. lytte til musikk og lese lekser, eller snakke og rydde rommet? Eller trenger du å fokusere på én ting av gangen?",
    33: "I en telefonsamtale (der du ikke kan se ansiktet til den du snakker med) – klarer du å vite når den andre er ferdig med å snakke og det er din tur?",
    34: "Liker du å gjøre ting SPONTANT – uten plan, bare finne på noe i øyeblikket? Eller foretrekker du å planlegge og vite hva som skal skje?",
    35: "Hender det at alle rundt deg ler av en vits, men det tar litt tid før du skjønner hva som er morsomt – eller at du trenger å få vitsen forklart?",
    36: "Kan du lese ansiktsuttrykk godt? F.eks. se om noen er lei seg, glad, sint, nervøs eller skuffet bare ved å se på ansiktet deres?",
    37: "Hvis du holder på med noe og blir avbrutt – klarer du lett å begynne igjen der du slapp? Eller er det frustrerende og vanskelig å komme tilbake til det?",
    38: "«Small-talk» er lett, uformell prat med folk du ikke kjenner så godt – som naboer, kjøpmannsdisken, eller nye klassekamerater. Er du komfortabel med det?",
    39: "Merker du at folk snakker om deg på andre siden av rommet, selv om du ikke hører ordene tydelig? Er du sensitiv for slike sosiale signaler rundt deg?",
    40: "Når du leser en bok eller artikkel – klarer du lett å forstå hva forfatteren egentlig vil si? Hva budskapet er, og hva de har tenkt på?",
    41: "Samler du på noe – eller liker du å sortere og kategorisere ting systematisk? F.eks. figurer, kort, musikk, filmer, fakta, eller noe annet du ordner i kategorier?",
    42: "Klarer du å 'sette deg inn i' en annen persons situasjon? F.eks. forestille deg hvordan det kjennes å leve et helt annet liv, ha andre tanker og andre erfaringer enn deg?",
    43: "Liker du å ha en detaljert plan for ting du skal gjøre? F.eks. vite nøyaktig hva som skjer, hvem som er der og i hvilken rekkefølge ting skjer?",
    44: "Liker du sosiale begivenheter generelt – som bursdagsfester, familiesammenkomster, klassefester og lignende arrangementer?",
    45: "Er det vanskelig å forstå HVORFOR folk gjør det de gjør? F.eks. forstå om en person er snill, vil lure deg, er sjalu, eller bare er genuint vennlig?",
    46: "Blir du urolig eller nervøs når du er i en situasjon du ikke har vært i før? F.eks. nytt sted, ny skole, ukjente folk eller aktiviteter du ikke kjenner fra før?",
    47: "Synes du det er hyggelig å bli kjent med nye folk – folk du aldri har møtt før?",
    48: "En diplomat er flink til å si ting på en måte som ikke sårer noen og som får folk til å forstå hverandre. Er du flink til å håndtere vanskelige situasjoner mellom folk?",
    49: "Husker du vennenes bursdager og andre viktige datoer? Er du generelt god til å huske slike ting?",
    50: "«Late som»-lek er fantasilek der man later som man er noe annet – at pinnene er sverd, teppet er et skip, eller at man er en karakter i et eventyr. Er slik lek lett for deg?",
  },
};
